### ISSUE TITLE
Add this LS to nvim-lspconfing

### ISSUE THREAD

**Issue by otavioschwanck** [qiuxiang/solidity-ls#3]
Would be awesome to have this LS in https://github.com/neovim/nvim-lspconfig

**Comment by qiuxiang** [comment]
I have never used nvim-lspconfig, let me try it first.

**Comment by weirongxu** [comment]
This is a configuration like the something in [coc-settings.json](https://github.com/neoclide/coc.nvim/wiki/Language-servers), the relevant files are at https://github.com/neovim/nvim-lspconfig/tree/master/lua/lspconfig/server_configurations, I think it need someone to submit a PR to nvim-lspconfig

**Comment by qiuxiang** [comment]
```lua
local lspconfig = require 'lspconfig'
local configs = require 'lspconfig.configs'
configs.solidity = {
  default_config = {
    cmd = { 'solidity-ls', '--stdio' },
    filetypes = { 'solidity' },
    root_dir = lspconfig.util.find_git_ancestor,
    single_file_support = true,
  },
}
lspconfig.solidity.setup {}
```

**Comment by otavioschwanck** [comment]
awesome!

**Comment by otavioschwanck** [comment]
> ```lua
> local configs = require 'lspconfig.configs'
> configs.solidity = {
>   default_config = {
>     cmd = { 'solidity-ls', '--stdio' },
>     filetypes = { 'solidity' },
>     root_dir = lspconfig.util.find_git_ancestor,
>     single_file_support = true,
>   },
> }
> lspconfig.solidity.setup {}
> ```

how can i do the remappings with nvim lspconfig?

**Comment by qiuxiang** [comment]
should be

```lua
local lspconfig = require 'lspconfig'
local configs = require 'lspconfig.configs'
local settings = {
  solidity = { remapping = { ... } }
}
configs.solidity = {
  default_config = {
    cmd = { 'solidity-ls', '--stdio' },
    filetypes = { 'solidity' },
    root_dir = lspconfig.util.find_git_ancestor,
    single_file_support = true,
  },
}
lspconfig.solidity.setup { settings = settings }
```

**Comment by nonogakhi** [comment]
Hi, I'm new to lua and solidity. Can you mention what goes into 

> remapping = { ... }

**Comment by nonogakhi** [comment]
I think mentioning remapping in the settings is redundant as for know. I put remapping.txt generated by foundry and the import issues is resolved.
Thanks
