### ISSUE TITLE
Unexpected end of JSON input error

### ISSUE THREAD

**Issue by oldnicolas** [qiuxiang/solidity-ls#4]
Can not set it with neovim lsp.
I got the following error from lsp logs in Neovim:
`[ERROR][2022-07-12 15:49:45] .../vim/lsp/rpc.lua:439	"rpc"	"solidity-ls"	"stderr"	"undefined:1\n\n\nSyntaxError: Unexpected end of JSON input\n    at JSON.parse (<anonymous>)\n    at Socket.<anonymous> (/home/nicolas/.local/lib/node_modules/solidity-ls/dist/index.js:53:50)\n    at Socket.emit (node:events:549:35)\n    at endReadableNT (node:internal/streams/readable:1359:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n\nNode.js v18.5.0\n"
`

My neovim version:
NVIM v0.8.0-dev+602-g8b75ca734
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

My lsp config: just copy the readme neovim lsp config

solidity-ls has been installed

**Comment by qiuxiang** [comment]
u need native solc

**Comment by oldnicolas** [comment]
Thanks, solved!
