### ISSUE TITLE
ParserError

### ISSUE THREAD

**Issue by oldnicolas** [qiuxiang/solidity-ls#5]
ParserError: Source "hardhat/console.sol" not found: File not found. Searched the following locations: "/Users/albert/nicolas 
 /my-uniswap/contracts", "/Users/albert/nicolas/my-uniswap/contracts/node_modules".

My `node_modules` is under `root_dir` not the `contracts` directory, how can language server find it? Thanks.

**Comment by qiuxiang** [comment]
u should open sol file from project root dir

**Comment by oldnicolas** [comment]
But the project structure need my sol file under `contracts` directory, the language server can not search path like "/Users/albert/nicolas/my-uniswap/node_modules"  directly?

**Comment by qiuxiang** [comment]
i mean `vi contracts/a.sol` not `cd contracts && vi a.sol`

**Comment by oldnicolas** [comment]
I tried it but the error still exists.

**Comment by qiuxiang** [comment]
can u provide a sample project to reproduce this issue?

**Comment by qiuxiang** [comment]
my project:

![Screenshot 2022-07-28 09 15 06](https://user-images.githubusercontent.com/1709072/181399352-606e44d1-7886-4877-bc48-61efc0b8694c.png)
![Screenshot 2022-07-28 09 14 58](https://user-images.githubusercontent.com/1709072/181399348-2de90a2f-c726-4e53-8c0f-af447c29561e.png)

**Comment by oldnicolas** [comment]
I just create a sample project with hardhat:
`mkdir test && cd test`
`npm init -y`
`npm install --save-dev hardhat`
`npx hardhat` follow prompt and create a sample javascript project

Then I open the default `contracts/Lock.sol` and get the error.

**Comment by qiuxiang** [comment]
I get it, you are using nvim lspconfig. just `git init` in project root. if your config is

```
configs.solidity = {
  default_config = {
    cmd = { 'solidity-ls', '--stdio' },
    filetypes = { 'solidity' },
    root_dir = lspconfig.util.find_git_ancestor,
    single_file_support = true,
  },
}
```

or u can change `root_dir` detection to `lspconfig.util.root_pattern('Makefile', '.git', '*.gpr', '*.adc')`

**Comment by oldnicolas** [comment]
Problem solved, sorry for your time because of my lspconfig setup, thanks for the detailed explanation.
